#+title: Solutions to Exercises 0.7 to 0.13 of Pedoe's Geometry
#+author: Joel McBride
#+options: num:nil toc:nil

* 0.7
\begin{align*}
&(1 + i)^2 \\
&= (\sqrt{2}(\frac{1}{\sqrt{2}} + \frac{1}{\sqrt{2}}i))^2 \\
&= (\sqrt{2} (\cos(\frac{\pi}{4}) + i \sin(\frac{\pi}{4})))^2 \\
\textrm{By De Moivre's theorem} \\
&= 2(\cos(\frac{\pi}{2}) + i \sin(\frac{\pi}{2})) \\
&= 2i
\end{align*}

From above it can be seen that the modulus is 2, amplitude is \( \frac{\pi}{2} \).

\begin{align*} 
&  (1 - i)^{2} \\
&= [\sqrt{2}(\cos(-\frac{\pi}{4}) + \sin(-\frac{\pi}{4}))]^2 \\
&= 2(\cos(-\frac{\pi}{2}) + \sin(-\frac{\pi}{2})i) \\
&= -2i
\end{align*}

It can be seen that the modulus is 2 and the amplitude is \( -\frac{\pi}{2} \).

\begin{align*}
\frac{(1 + i)^2}{(1 - i)^2} &= \frac{2i}{-2i} \\
                            &= -1 \\
                            &= 1 \cdot (cos(\pi) + sin(\pi))
\end{align*}

It can be seen that the modulus is 1 and the amplitude is \( \pi \).

\begin{align*}
\frac{(1 - i)^2}{(1 + i)^2} &= \frac{-2i}{2i} \\
                            &= -1 \\
                            &= 1 \cdot (cos(\pi) + sin(\pi))
\end{align*}

The modulus and amplitude are the same as the previous number; modulus is 1 and amplitude \( \pi \).

* 0.8
** Configurations
*Note:* Possible values should be \( \theta \), \( -\theta \), \( 2\pi - \theta \), \( -2\pi + \theta \).

If there is no discontinuity in \( \theta \) then,
\( am(\frac{c-a}{c-b}) = \theta \) if c-a leads c-b and
\( am(\frac{c-a}{c-b}) = -\theta \) if c-b leads c-a.

If there is a discontinuity in \( \theta \) then,
\( am(\frac{c-a}{c-b}) = 2\pi - \theta \) if c-a leads c-b and
\( am(\frac{c-a}{c-b}) = -2\pi + \theta \) if c-b leads c-a.

* 0.9 [Incomplete]
One family of circles is 

\begin{align*}
\frac{z-a}{z-b} \overline{\frac{z-a}{z-b}} &= r(\cos(\phi) + \sin(\phi)i) \cdot \overline{r(\cos(\phi) + \sin(\phi)i)} \\
\frac{|z-a|^2}{|z-b|^2} &= r^2
\end{align*}

This describes a circle by exercise 0.6.
We can see that as r approaches 0, z approaches a and as r goes to infinity z approaches b so the limit points of this family of circles is a and b. 

The other family is

\begin{align*}
am(\frac{z - a}{z - b}) = \phi
\end{align*}

This describes a circle by the inscribed angle theorem.

https://en.wikipedia.org/wiki/Apollonian_circles shows why the two families of circles are orthogonal coaxial systems of circles.

* 0.10 Show that the 3 roots of \( z^3 = 1 \) are the vertices of an equilateral triangle on the circle |z| = 1
We observe that \( \cos(\frac{2k\pi}{3}) + i\sin(\frac{2k\pi}{3}) \) satisfies the equation by De Moivre's theorem.
The values of k where the amplitude is described unambiguous as defined in the book are \( k = -1, 0, 1 \).

** We will show that the points lie on the circle \( |z| = 1 \)
*** For k = 0
\begin{align*}
& \cos(0) + i\sin(0) \\
=& 1
\end{align*}

This point is a distance of \( |1| = 1 \) away so it lies on the circle.

*** For k = 1
\begin{align*}
& \cos(\frac{2\pi}{3}) + i \sin(\frac{2\pi}{3})
&= -\frac{1}{2} + i \frac{\sqrt{3}}{2}
\end{align*}

This point is a distance of \( |-\frac{1}{2} + i \frac{\sqrt{3}}{2}| = \frac{1}{4} + \frac{3}{4} = 1 \) away so it lies on the circle.

*** For k = -1
\begin{align*}
& \cos(\frac{-2\pi}{3}) + i \sin(\frac{-2\pi}{3})
&= -\frac{1}{2} - i \frac{\sqrt{3}}{2}
\end{align*}

This point is a distance of \( |-\frac{1}{2} - i \frac{\sqrt{3}}{2}| = \frac{1}{4} + \frac{3}{4} = 1 \) away so it lies on the circle.

** We will show that the points are the vertices of an equilateral triangle
Let a, b, c be 1, \( -\frac{1}{2} + i\frac{\sqrt{3}}{2} \), \( -\frac{1}{2} - i\frac{\sqrt{3}}{2} \) respectively.
If and only if the points are vertices of an equilateral triangle then \( |a-b| = |b-c| = |c-a| \).
We will show that \( |a-b| = |b-c| = |c-a| \).

*** \( |a - b| \)
\begin{align*}
& |1 - (-\frac{1}{2} + i\frac{\sqrt{3}}{2})| \\
&= |\frac{3}{2} + i\frac{\sqrt{3}}{2}| \\
&= \sqrt{\frac{9}{4} + \frac{3}{4}} \\
&= \sqrt{3}
\end{align*}

*** \( |b - c| \)
\begin{align*}
& |(-\frac{1}{2} + i\frac{\sqrt{3}}{2} - (-\frac{1}{2} - i\frac{\sqrt{3}}{2})| \\
&= |i\frac{2\sqrt{3}}{2}| \\
&= \sqrt{3}
\end{align*}

*** \( |c - a| \)
\begin{align*}
& |(-\frac{1}{2} - i\frac{\sqrt{3}}{2} - 1)| \\
&= |-\frac{3}{2} - i\frac{\sqrt{3}}{2}| \\
&= \sqrt{\frac{9}{4} + \frac{3}{4}} \\
&= \sqrt{3}
\end{align*}

Since \( |a-b| = |b-c| = |c-a| \), the three points are also the vertices of an equilateral triangle.
* 0.11 Show that if roots of \( z^3 =1 \) are 1, \( \omega \), \( \omega' \) then 
** \( \omega' = \omega^2 \)
\begin{align*}
(z - 1)(z - \omega)(z - \omega') &= 0 \\
z^3 + (-\omega - 1 - \omega') z^2 + (\omega + \omega \omega' + \omega')z - \omega \omega' &= 0
\end{align*}

but \( z^3 = 1 \)

\begin{align*}
(-\omega - 1 - \omega') z^2 + (\omega + \omega \omega' + \omega')z + 1 - \omega \omega' &= 0
\end{align*}

In order for this to be true for all z, each coefficent of the powers of z must be 0.
This produces the following equations.

\begin{align}
1 + \omega + \omega' &= 0 \\
\omega + \omega \omega' + \omega' &= 0 \\
\omega \omega' &= 1
\end{align}

Substitude equation 1 into equation 4.

\begin{align*}
\omega( - \omega - 1) &= 1 \\
-\omega^2 - \omega &= 1
\end{align*}

Use equation 1 to replace \( \omega \)

\begin{align*}
-\omega^2 + \omega' + 1 &= 1 \\
\omega^2 = \omega'
\end{align*}

** \( 1 + \omega + \omega^2 = 0 \)
Replacing \( \omega' \) with \( \omega^2 \) in equation 1 results in \( 1 + \omega + \omega^2 = 0 \).

* 0.12
Expanding \( (x + y + z)(x^2 + y^2 + z^2 - xy - yz - zx) \) results in \( x^3 + y^3 + z^3 - 3xyz \).

Let roots of \( x^3 \) be \( 1 \), \( \omega \), \( \omega^2 \).
These are also the roots of \( y^3 \), \( z^3 \) as changing the variable name doesn't change the value of the roots.

Expanding \( (x + \omega y + \omega^2 z)(x + \omega^2 y + \omega z) \) results in

\begin{align*}
& x^2 + (\omega^2 + \omega)xy + (\omega + \omega^2)xz + \omega^3 y^2 + (\omega^2 + \omega^4)yz + \omega^3 z^2 \\
& x^2 + y^2 + z^2 + \omega(1+\omega)xy + \omega(1+\omega)xz \omega(1+\omega)yz
\end{align*}

which equals \( x^2 + y^2 + z^2 - xy - xz - yz \) by the equations of the previous question.
Therefore,

\begin{align}
(x + y + z)(x + \omega y + \omega^2 z)(x + \omega^2 y + \omega z) = (x + y + z)(x^2 + y^2 + z^2 - xy - yz - zx)
\end{align}

* 0.13
** \( z^4 \)
\begin{align*}
z^4 &= 1 \\
(\cos\frac{2\pi k}{4} + \sin\frac{2\pi k}{4})^4 &= 1\\
\textrm{By De Moivre's theorem}
\cos{2\pi k} + \sin{2\pi k} &= 1
\end{align*}

Therefore, \( \cos\frac{2\pi k}{4} + \sin\frac{2\pi k}{4})^4 \) are solutions to \( z^4 \).
k ranges from -1, 0, 1, 2.

The four points are (1,0), (0,1), (-1,0), (0,-1).

** \( z^5 \)
By same argument as \( z^4 \), solutions to \( z^5 \) are \( \cos\frac{2\pi k}{5} + \sin\frac{2\pi k}{5}) \) are solutions to \( z^4 \).
k ranges from -2, -1, 0, 1, 2.

The five points are (1,0),
(\( \cos \frac{2\pi}{5} \),\( \sin \frac{2\pi}{5} \)),
(\( \cos \frac{4\pi}{5} \),\( \sin \frac{4\pi}{5} \)), 
(\( \cos \frac{-4\pi}{5} \),\( \sin \frac{-4\pi}{5} \)), 
(\( \cos \frac{-2\pi}{5} \),\( \sin \frac{-2\pi}{5} \)).

** \( z^n \)
In general the roots of \( z^n \) are the vertices of an n-gon in the Argand plane.
