#+title: Solutions to Exercises 4.1 to 4.5 of Pedoe's "Geometry: A Comprehensive Course"
#+author: Joel McBride
#+options: num:nil toc:nil

* 4.1
** Converse of Menelaus' theorem
The converse statement is: For a given triangle \( ABC \) and three points \( L = xB + x'C \), \( M = yC + y'A \), and \( N = zA + z'B \) where \( x+x'=y+y'=z+z' \) on the sides of the triangle, if \( xyz = -x'y'z' \) then the points \( L \), \( M \), and \( N \) are collinear.
*** Proof
Suppose \( LM \) meets \( AB \) at point \( N' = wA + w'B \) where \( w+w'=1 \). By Menelaus' theorem, \( xyw = -x'y'w' \). But \( xyz=x'y'z' \) therefore \( z=w \) and \( z'=w' \) which means \( N' = N \). Since \( N \) exists by hypothesis, the supposition is true. Therefore, \( L \), \( M \), and \( N \) are collinear.
QED

** Converse of Ceva's theorem
The converse statement is: For a given triangle \( ABC \) and points \( L = xB + x'C \), \( M = yC + y'A \), and \( N = zA + z'B \) where \( x+x'=y+y'=z+z' \) on the side of the triangle, if \( xyz = x'y'z' \) then \( AL \), \( BM \), and \( CN \) are concurrent.

*** Proof
Let \( P \) be the intersection of \( AL \) and \( BM \). Let \( N' = wA + w'B \) be the point where \( CP \) cuts \( AB \). By Ceva's theorem, \( xyw = xyw' \). But \( xyz=x'y'z' \) therefore \( w=z \) and \( w'=z' \). Hence \(N=N' \) and all three lines intersect at point P.
QED

* 4.2
